# Part 1- Data Cleaning 

### Data Cleaning for Crash Data for Australia  

Link to dataset:- https://www.kaggle.com/datasets/deepcontractor/australian-fatal-car-accident-data-19892021

In [1]:
#importing all the necessary libraries
import numpy as np
import pandas as pd
import os 
import datetime as dt
import math
import seaborn as sns

In [2]:
#reading the data
df=pd.read_csv('Crash_Data.csv')
df=pd.DataFrame(df)

C:\Users\yashp\AppData\Local\Temp\ipykernel_3656\3279786197.py:2: DtypeWarning: Columns (10,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('Crash_Data.csv')


In [3]:
df.shape

(52843, 23)

In [4]:
df.columns

Index(['Crash ID', 'State', 'Month', 'Year', 'Dayweek', 'Time', 'Crash Type',
       'Bus Involvement', 'Heavy Rigid Truck Involvement',
       'Articulated Truck Involvement', 'Speed Limit', 'Road User', 'Gender',
       'Age', 'National Remoteness Areas', 'SA4 Name 2016',
       'National LGA Name 2017', 'National Road Type', 'Christmas Period',
       'Easter Period', 'Age Group', 'Day of week', 'Time of day'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52843 entries, 0 to 52842
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype 
---  ------                         --------------  ----- 
 0   Crash ID                       52843 non-null  int64 
 1   State                          52843 non-null  object
 2   Month                          52843 non-null  int64 
 3   Year                           52843 non-null  int64 
 4   Dayweek                        52843 non-null  object
 5   Time                           52803 non-null  object
 6   Crash Type                     52843 non-null  object
 7   Bus Involvement                52821 non-null  object
 8   Heavy Rigid Truck Involvement  32328 non-null  object
 9   Articulated Truck Involvement  52821 non-null  object
 10  Speed Limit                    52141 non-null  object
 11  Road User                      52843 non-null  object
 12  Gender                         52816 non-null  object
 13  A

In [6]:
df.head(5)

Crash ID State  Month  Year   Dayweek   Time Crash Type Bus Involvement  \
0  20212133   Vic      9  2021    Sunday   0:30     Single             NaN   
1  20214022    SA      9  2021  Saturday  23:31   Multiple              No   
2  20212096   Vic      9  2021  Saturday  23:00     Single             NaN   
3  20212145   Vic      9  2021  Saturday  22:25     Single             NaN   
4  20212075   Vic      9  2021  Saturday   5:15     Single             NaN   

  Heavy Rigid Truck Involvement Articulated Truck Involvement  ... Age  \
0                           NaN                           NaN  ...  38   
1                            No                            No  ...  28   
2                           NaN                           NaN  ...  19   
3                           NaN                           NaN  ...  23   
4                           NaN                           NaN  ...  46   

   National Remoteness Areas           SA4 Name 2016  National LGA Name 2017  \
0   Inner Regional Australia  Melbourne - Outer East        Yarra Ranges (S)   
1  Major Cities of Australia        Adelaide - North            Playford (C)   
2   Inner Regional Australia                    Hume         Wangaratta (RC)   
3   Outer Regional Australia                    Hume         Wangaratta (RC)   
4  Major Cities of Australia  Melbourne - South East               Casey (C)   

  National Road Type Christmas Period Easter Period Age Group Day of week  \
0      Arterial Road               No            No  26_to_39     Weekend   
1                NaN               No            No  26_to_39     Weekend   
2        Access road               No            No  17_to_25     Weekend   
3      Arterial Road               No            No  17_to_25     Weekend   
4         Local Road               No            No  40_to_64     Weekend   

  Time of day  
0       Night  
1       Night  
2       Night  
3       Night  
4       Night  

[5 rows x 23 columns]

In [7]:
#Checking for null values
df.isnull().sum()

Crash ID                             0
State                                0
Month                                0
Year                                 0
Dayweek                              0
Time                                40
Crash Type                           0
Bus Involvement                     22
Heavy Rigid Truck Involvement    20515
Articulated Truck Involvement       22
Speed Limit                        702
Road User                            0
Gender                              27
Age                                  0
National Remoteness Areas        45965
SA4 Name 2016                    45951
National LGA Name 2017           45950
National Road Type               45966
Christmas Period                     0
Easter Period                        0
Age Group                           90
Day of week                          0
Time of day                          0
dtype: int64

In [8]:
#droping columns with maximum null values
df=df.drop(columns=['National Remoteness Areas','SA4 Name 2016','National LGA Name 2017','National Road Type'],axis=1)

In [9]:
#Checking for null values
df.isnull().sum()

Crash ID                             0
State                                0
Month                                0
Year                                 0
Dayweek                              0
Time                                40
Crash Type                           0
Bus Involvement                     22
Heavy Rigid Truck Involvement    20515
Articulated Truck Involvement       22
Speed Limit                        702
Road User                            0
Gender                              27
Age                                  0
Christmas Period                     0
Easter Period                        0
Age Group                           90
Day of week                          0
Time of day                          0
dtype: int64

### Checking all the values in the columns 

In [10]:
df['Heavy Rigid Truck Involvement'].unique()

array([nan, 'No', 'Yes'], dtype=object)

In [11]:
df['Articulated Truck Involvement'].unique()

array([nan, 'No', 'Yes'], dtype=object)

In [12]:
df['Bus Involvement'].unique()

array([nan, 'No', 'Yes'], dtype=object)

In [13]:
#Changing all the nan to No in the column
df['Heavy Rigid Truck Involvement'].fillna("No", inplace = True)

In [14]:
df['Heavy Rigid Truck Involvement'].unique()

array(['No', 'Yes'], dtype=object)

In [15]:
#Changing all the nan to No in the column
df['Articulated Truck Involvement'].fillna("No", inplace = True)

In [16]:
df['Articulated Truck Involvement'].unique()

array(['No', 'Yes'], dtype=object)

In [17]:
#Changing all the nan to No in the column
df['Bus Involvement'].fillna("No", inplace = True)

In [18]:
df['Bus Involvement'].unique()

array(['No', 'Yes'], dtype=object)

In [19]:
#Checking for null values
df.isnull().sum()

Crash ID                           0
State                              0
Month                              0
Year                               0
Dayweek                            0
Time                              40
Crash Type                         0
Bus Involvement                    0
Heavy Rigid Truck Involvement      0
Articulated Truck Involvement      0
Speed Limit                      702
Road User                          0
Gender                            27
Age                                0
Christmas Period                   0
Easter Period                      0
Age Group                         90
Day of week                        0
Time of day                        0
dtype: int64

In [20]:
df['Speed Limit'].unique()

array([nan, '110', '100', '60', '80', '50', '70', '90', '40', '130', '20',
       '10', '30', '25', '15', '<40', '5', 'Unspecified', '75', 110, 100,
       60, -9, 80, 90, 70, 40, 50, 30, 20, 75], dtype=object)

In [21]:
#replacing all the nan with 0 
df['Speed Limit'].fillna("0", inplace = True)

In [22]:
df['Speed Limit'].unique()

array(['0', '110', '100', '60', '80', '50', '70', '90', '40', '130', '20',
       '10', '30', '25', '15', '<40', '5', 'Unspecified', '75', 110, 100,
       60, -9, 80, 90, 70, 40, 50, 30, 20, 75], dtype=object)

In [23]:
#replacing all the -9 with 0 as speed limit cannot be negative 
df['Speed Limit'] = df['Speed Limit'].replace([-9], '0')

In [24]:
df['Speed Limit'].unique()

array(['0', '110', '100', '60', '80', '50', '70', '90', '40', '130', '20',
       '10', '30', '25', '15', '<40', '5', 'Unspecified', '75', 110, 100,
       60, 80, 90, 70, 40, 50, 30, 20, 75], dtype=object)

In [25]:
#to convert the whole column to int getting rid of < sign 
df['Speed Limit'] = df['Speed Limit'].replace(['<40'], 39)

In [26]:
#to convert the whole column to int getting rid of Unspecified
df['Speed Limit'] = df['Speed Limit'].replace(['Unspecified'], 0)

In [27]:
#typecasting the whole column as int
df['Speed Limit']=df['Speed Limit'].astype(int)

In [28]:
df['Speed Limit'].unique()

array([  0, 110, 100,  60,  80,  50,  70,  90,  40, 130,  20,  10,  30,
        25,  15,  39,   5,  75])

In [29]:
#Checking for null values
df.isnull().sum()

Crash ID                          0
State                             0
Month                             0
Year                              0
Dayweek                           0
Time                             40
Crash Type                        0
Bus Involvement                   0
Heavy Rigid Truck Involvement     0
Articulated Truck Involvement     0
Speed Limit                       0
Road User                         0
Gender                           27
Age                               0
Christmas Period                  0
Easter Period                     0
Age Group                        90
Day of week                       0
Time of day                       0
dtype: int64

In [30]:
df['Gender'].unique()

array(['Male', 'Female', nan, 'Unspecified'], dtype=object)

In [31]:
#filling the nulls with Uspecified to make the column more complete 
df['Gender'].fillna("Unspecified", inplace = True)

In [32]:
df['Gender'].unique()

array(['Male', 'Female', 'Unspecified'], dtype=object)

In [33]:
#Checking for null values
df.isnull().sum()

Crash ID                          0
State                             0
Month                             0
Year                              0
Dayweek                           0
Time                             40
Crash Type                        0
Bus Involvement                   0
Heavy Rigid Truck Involvement     0
Articulated Truck Involvement     0
Speed Limit                       0
Road User                         0
Gender                            0
Age                               0
Christmas Period                  0
Easter Period                     0
Age Group                        90
Day of week                       0
Time of day                       0
dtype: int64

In [34]:
df['Time'].unique()

array(['0:30', '23:31', '23:00', ..., '3:42', '22:33', '6:57'],
      dtype=object)

In [35]:
#storing the index of the null values 
x=df[df['Time'].isnull()].index.tolist()

In [36]:
#checking what time of the day is it when the values are null in the Time Column 
values = df['Time of day'].iloc[x]
values

11088    Night
16478    Night
16849    Night
17445    Night
17449    Night
20632    Night
20644    Night
20648    Night
21488    Night
21599    Night
22929    Night
24042    Night
25941    Night
27418    Night
27628    Night
28007    Night
28245    Night
30063    Night
32712    Night
33277    Night
33312    Night
33428    Night
37274    Night
37735    Night
37753    Night
37881    Night
37882    Night
37883    Night
37924    Night
38249    Night
41535    Night
41677    Night
41795    Night
41889    Night
42070    Night
42406    Night
46073    Night
47198    Night
48712    Night
52714    Night
Name: Time of day, dtype: object

In [37]:
#Since all are night we will fill the nulls with 10 pm as a value 
df['Time'].fillna('22:00', inplace = True)

In [38]:
#Checking for null values
df.isnull().sum()

Crash ID                          0
State                             0
Month                             0
Year                              0
Dayweek                           0
Time                              0
Crash Type                        0
Bus Involvement                   0
Heavy Rigid Truck Involvement     0
Articulated Truck Involvement     0
Speed Limit                       0
Road User                         0
Gender                            0
Age                               0
Christmas Period                  0
Easter Period                     0
Age Group                        90
Day of week                       0
Time of day                       0
dtype: int64

In [39]:
#storing the index of the null values 
x=df[df['Age Group'].isnull()].index.tolist()

In [40]:
df['Age Group'].unique()

array(['26_to_39', '17_to_25', '40_to_64', '0_to_16', '65_to_74',
       '75_or_older', nan], dtype=object)

In [41]:
df['Age'].unique()

array([ 38,  28,  19,  23,  46,  20,  17,   2,  47,  24,  52,  49,  32,
        34,  26,  56,  11,  45,  61,  36,  71,  15,  27,  31,  86,  37,
        58,  22,  42,  62,  64,  51,  83,  60,  74,  70,  66,  72,  68,
        69,  78,   6,  76,  84,  50,  16,  63,  77,  85,  90,  10,  39,
         4,  35,  43,  59,  40,  18,  29,  48,  67,   8,  79,  75,  41,
        25,  82,  -9,  80,  30,  33,  55,  73,  12,  44,  54,   7,   5,
        92,   9,  57,  53,  81,  87,  21,  14,  13,  65,  88,   1,  89,
         3,  91,  93,   0,  94,  97, 101,  95,  99,  96,  98, 100],
      dtype=int64)

In [42]:
#Cross checking the index with Age to know the age of missing values 
values = df['Age'].iloc[x]
values

158     -9
734     -9
1649    -9
1650    -9
1651    -9
        ..
50764   -9
50765   -9
50766   -9
50797   -9
52608   -9
Name: Age, Length: 90, dtype: int64

In [43]:
#Since all values are -9 we replace it with NA  
df['Age'] = df['Age'].replace(['-9'], "NA")

In [44]:
#Since all values of age are -9 we replace it with NA
df['Age Group'].fillna('NA', inplace = True)

In [45]:
#Checking for null values
df.isnull().sum()

Crash ID                         0
State                            0
Month                            0
Year                             0
Dayweek                          0
Time                             0
Crash Type                       0
Bus Involvement                  0
Heavy Rigid Truck Involvement    0
Articulated Truck Involvement    0
Speed Limit                      0
Road User                        0
Gender                           0
Age                              0
Christmas Period                 0
Easter Period                    0
Age Group                        0
Day of week                      0
Time of day                      0
dtype: int64

## Storing the cleaned data 

In [46]:
#storing the cleaned data set in a new csv file 
df.to_csv('cleanedCrash.csv',index=False)

In [47]:
#reading the cleaned data to cross check 
cf=pd.read_csv('cleanedCrash.csv')

In [48]:
#displaying the first 10 data values 
cf.head(10)

Crash ID State  Month  Year    Dayweek   Time Crash Type Bus Involvement  \
0  20212133   Vic      9  2021     Sunday   0:30     Single              No   
1  20214022    SA      9  2021   Saturday  23:31   Multiple              No   
2  20212096   Vic      9  2021   Saturday  23:00     Single              No   
3  20212145   Vic      9  2021   Saturday  22:25     Single              No   
4  20212075   Vic      9  2021   Saturday   5:15     Single              No   
5  20213034   Qld      9  2021   Saturday   4:00   Multiple              No   
6  20215071    WA      9  2021   Saturday  19:10     Single              No   
7  20212015   Vic      9  2021   Thursday  19:33   Multiple              No   
8  20213026   Qld      9  2021  Wednesday  23:00   Multiple              No   
9  20213092   Qld      9  2021   Saturday   2:00     Single              No   

  Heavy Rigid Truck Involvement Articulated Truck Involvement  Speed Limit  \
0                            No                            No            0   
1                            No                            No          110   
2                            No                            No            0   
3                            No                            No            0   
4                            No                            No            0   
5                            No                            No          100   
6                            No                            No          100   
7                            No                            No            0   
8                            No                            No            0   
9                            No                            No           60   

          Road User  Gender  Age Christmas Period Easter Period Age Group  \
0  Motorcycle rider    Male   38               No            No  26_to_39   
1        Pedestrian  Female   28               No            No  26_to_39   
2         Passenger    Male   19               No            No  17_to_25   
3            Driver    Male   23               No            No  17_to_25   
4  Motorcycle rider    Male   46               No            No  40_to_64   
5  Motorcycle rider    Male   19               No            No  17_to_25   
6            Driver  Female   20               No            No  17_to_25   
7          Other/-9    Male   17               No            No  17_to_25   
8         Passenger  Female    2               No            No   0_to_16   
9            Driver    Male   47               No            No  40_to_64   

  Day of week Time of day  
0     Weekend       Night  
1     Weekend       Night  
2     Weekend       Night  
3     Weekend       Night  
4     Weekend       Night  
5     Weekend       Night  
6     Weekend       Night  
7     Weekday       Night  
8     Weekday       Night  
9     Weekend       Night

In [49]:
cf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52843 entries, 0 to 52842
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype 
---  ------                         --------------  ----- 
 0   Crash ID                       52843 non-null  int64 
 1   State                          52843 non-null  object
 2   Month                          52843 non-null  int64 
 3   Year                           52843 non-null  int64 
 4   Dayweek                        52843 non-null  object
 5   Time                           52843 non-null  object
 6   Crash Type                     52843 non-null  object
 7   Bus Involvement                52843 non-null  object
 8   Heavy Rigid Truck Involvement  52843 non-null  object
 9   Articulated Truck Involvement  52843 non-null  object
 10  Speed Limit                    52843 non-null  int64 
 11  Road User                      52843 non-null  object
 12  Gender                         52843 non-null  object
 13  A